version: "3.8"

services:

  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app
    volumes:
      - mongo:/data/db

networks:
  app:
    driver: bridge

volumes:
  mongo:
    driver: local