services:

  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=3000

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - app
    volumes:
      - mongo:/data/db

networks:
  app:
    driver: bridge

volumes:
  mongo:
    driver: local